### ISSUE TITLE
Suffix Right Align

### ISSUE THREAD

**Issue by EcoSMP** [NEZNAMY/TAB#1174]
### Server version

Purpur 1.20.2

### TAB version

4.1.2

### Describe the bug

Hey, before the latest update players' suffix would always align on the right side of the tab list. After the update, they are directly next to their name and not aligned on the right side. 

### Expected behavior

We expect that the suffix will be aligned on the right side.

### Steps to reproduce

I am unsure how to replicate this, unfortunately. I apologize.

### Additional info

It's been too long since this was set up, so I don't remember how this was done. Hoping you can help me out. Thank you for your time!

### Checklist

- [X] I am running latest version of the plugin
- [X] I have read the wiki to make sure it's not an issue with configuration
- [ ] I ticked all of the boxes without actually reading them
- [X] I have read the Compatibility wiki page and am not trying to run the plugin on an unsupported server version / platform
- [X] I am willing to cooperate to get this issue resolved faster, including providing any additional information requested or testing new builds

**Comment by NEZNAMY** [comment]
The feature was removed in 4.1.0, because it was added to minecraft itself in 1.20.3. It was also hard to both maintain and use (especially with special symbols), so I decided it will be better to remove it. See [playerlist objective](https://github.com/NEZNAMY/TAB/wiki/Feature-guide:-Playerlist-Objective) feature for more info.
