### ISSUE TITLE
no postgresql support

### ISSUE THREAD

**Issue by SantaSpeen** [NEZNAMY/TAB#1196]
### TAB version

4.1.2

### Software causing compatibility issue

Hello, i khow, this is "Feature request", sorry, but all my plugins and services sets to use postgresql
Only TAB uses mysql
Can u add postgresql support?

### Checklist

- [X] I am running latest version of the plugin
- [ ] I ticked all of the boxes without actually reading them
- [X] The compatibility wiki page does not mention this incompatibility
- [X] I am willing to cooperate to get this issue resolved faster, including providing any additional information requested or testing new builds

**Comment by NEZNAMY** [comment]
* [Feature requests are closed](https://github.com/NEZNAMY/TAB?tab=readme-ov-file#provided-services)
* `The compatibility wiki page does not mention this incompatibility` - not a compatibility issue, it's a missing compatibility
* Even MySQL support itself is highly redundant, because if you want to sync groups between servers, the easiest way is to use the plugin on the proxy. What's preventing you from doing it?

**Comment by SantaSpeen** [comment]
i have 4 proxy servers 😅

**Comment by NEZNAMY** [comment]
You can do what other people do - configure prefixes in LP and just use TAB to display them. Same result.

**Comment by SantaSpeen** [comment]
If u don't into my feature request, no problems, thats my issue
