### ISSUE TITLE
TAB incompatible with future versions of Paper

### ISSUE THREAD

**Issue by kennytv** [NEZNAMY/TAB#1220]
### TAB version

4.1.2

### Software causing compatibility issue

This is a heads-up since this will only be an issue in the future, but due to parsing the CB relocation version directly, TAB will break on Paper in the future. Here is the stacktrace: https://paste.gg/p/anonymous/3e1ab07ec6e74fafaac30a2cdabddbc9

And here is more info on the topic/how to resolve it: https://forums.papermc.io/threads/paper-velocity-1-20-4.998/#post-2955

### Checklist

- [X] I am running latest version of the plugin
- [ ] I ticked all of the boxes without actually reading them
- [X] The compatibility wiki page does not mention this incompatibility
- [X] I am willing to cooperate to get this issue resolved faster, including providing any additional information requested or testing new builds

**Comment by NEZNAMY** [comment]
Hello, thanks for the info, I was already thinking about it and did [exactly that](https://github.com/NEZNAMY/TAB/commit/3ddf884c230c1b9eefbd11a574ecb063c6436d6b). Due to compatibility with older versions I cannot completely drop the package, so I was looking for a solution, but since I don't have the jar, I wouldn't be able to test it anyway. Do you have a downloadable paper jar without CB relocation / version packaging that I can play with?

**Comment by kennytv** [comment]
Uploaded one here: https://github.com/PaperMC/testing/releases/tag/no-relocation
Ideally only use that in a new server folder, since it is missing cleaning up of remapped jars
