### ISSUE TITLE
[RedisBungee] Tablist formatting fails to apply for players on other proxies

### ISSUE THREAD

**Issue by efekurbann** [NEZNAMY/TAB#1317]
### TAB version

4.1.5

### Software causing compatibility issue

RedisBungee (Velocity)

### Additional info

In our server, some groups has hex colors in their prefixes, to change the player's displayname. 
However, as the title says, while the players on the same proxy can see eachother's tablist names correctly. But if a player is on a different server than other is, colors are rounded to the nearest legacy code. Both server's config is the exact same. 

![image](https://github.com/NEZNAMY/TAB/assets/58657492/1c0fa98d-70a5-4490-a44b-9fef51a9d7af)

### Checklist

- [X] I am running latest version of the plugin
- [ ] I ticked all of the boxes without actually reading them
- [X] I am willing to cooperate to get this issue resolved faster, including providing any additional information requested or testing new builds
- [X] The compatibility wiki page does not mention this incompatibility

**Comment by NEZNAMY** [comment]
Could it be that it's the nametag format in tablist instead? Can you add something to tagsuffix and tabsuffix (something different) to confirm?

**Comment by efekurbann** [comment]
My apologies on lying about it being the latest. I'll update it tonight but didn't want to wait until then.
What changes do you want me to do on tag and tab suffix? And on both the servers?

**Comment by NEZNAMY** [comment]
Yes on both servers. You don't seem to have anything configured, so it's a great spot to put the testing text in. Just put in anything that will be different for each property to confirm it's indeed nametag format in tablist. Also try latest build from actions.

**Comment by efekurbann** [comment]
Updating to 5.0.0-SNAPSHOT from the latest build seem to break EVERYTHING. Here is a few error logs from my setup. https://mclo.gs/xRb3ojo

Player TAG names did not update nor show at all, TAB names did not update as well.
I guess 5.0.0 is a breaking update, especially for RedisBungee setups.
Even players were not able to see each others displaynames properly. However, /btab reload seemed to solve it.
I guess I'll stick to 4.1.6 for now.

If you need further testing, let me know.

**Comment by efekurbann** [comment]
However, when using 4.1.6 I noticed that whenever I update my parent group, It's colors are shown correctly.
Switching servers (Paper, not Velocity) seem to break it.

**Comment by NEZNAMY** [comment]
Fixed the error. Please try new build.

**Comment by efekurbann** [comment]
There is some progress. I can now see hex colors but I am not sure if it is fixed or not because I need to do /btab reload after rejoining the server. here is another err log: https://mclo.gs/ZAI0K5m

**Comment by NEZNAMY** [comment]
I am recoding the entire feature right now. Do you have discord? I need someone to test it for me (on a testing environment).

**Comment by efekurbann** [comment]
Sure. `@efekurban`

**Comment by MacTh3Mac** [comment]
Similar issue,    Velocity 3 (latest) TAB 5.0.0SNAPSHOT from methods.   Tablist formatting not applied for players on other proxies with redis-bungee,  including sort order.   

behaviour observed (ss taken from different proxy where players are located only player displayed correctly is myself:

![image](https://github.com/NEZNAMY/TAB/assets/34489434/496ef215-33c6-45c2-b6f5-4820df4a6873)

Behaviour Expected (similar to below (discounting the fact that this SS is on a layout) all players shown correctly:

![image](https://github.com/NEZNAMY/TAB/assets/34489434/8679226d-d632-4245-bc56-3718ea9c582b)

**Comment by NEZNAMY** [comment]
Their names look still colored though. Do you have tablist formatting anti-override enabled?

**Comment by MacTh3Mac** [comment]
```
tablist-name-formatting:
  enabled: true
  anti-override: true
  disable-condition: '%world%=disabledworld'
```

**Comment by MacTh3Mac** [comment]
color comes from backend bukkit server software and its nametags 

![image](https://github.com/NEZNAMY/TAB/assets/34489434/5f835115-55c8-4361-8068-aa677e6195ef)

**Comment by NEZNAMY** [comment]
Does it show correctly for players on the same proxy? Did you get errors.log file in TAB folder?

**Comment by MacTh3Mac** [comment]
Error log on fresh boot of Proxy.

28.06.2024 - 16:11:57 - [TAB v5.0.0-SNAPSHOT] An error was thrown when executing task
28.06.2024 - 16:11:57 - java.lang.IllegalStateException: java.io.EOFException
28.06.2024 - 16:11:57 - 	at com.google.common.io.ByteStreams$ByteArrayDataInputStream.readUTF(ByteStreams.java:458)
28.06.2024 - 16:11:57 - 	at me.neznamy.tab.shared.features.redis.message.PlayerJoin.read(PlayerJoin.java:49)
28.06.2024 - 16:11:57 - 	at me.neznamy.tab.shared.features.redis.message.Load.read(Load.java:34)
28.06.2024 - 16:11:57 - 	at me.neznamy.tab.shared.features.redis.RedisSupport.lambda$processMessage$1(RedisSupport.java:70)
28.06.2024 - 16:11:57 - 	at me.neznamy.tab.shared.cpu.TimedCaughtTask.run(TimedCaughtTask.java:28)
28.06.2024 - 16:11:57 - 	at me.neznamy.tab.shared.cpu.CaughtTask.run(CaughtTask.java:18)
28.06.2024 - 16:11:57 - 	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
28.06.2024 - 16:11:57 - 	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
28.06.2024 - 16:11:57 - 	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304)
28.06.2024 - 16:11:57 - 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
28.06.2024 - 16:11:57 - 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
28.06.2024 - 16:11:57 - 	at java.base/java.lang.Thread.run(Thread.java:833)
28.06.2024 - 16:11:57 - Caused by: java.io.EOFException: null
28.06.2024 - 16:11:57 - 	at java.base/java.io.DataInputStream.readFully(DataInputStream.java:203)
28.06.2024 - 16:11:57 - 	at java.base/java.io.DataInputStream.readUTF(DataInputStream.java:614)
28.06.2024 - 16:11:57 - 	at java.base/java.io.DataInputStream.readUTF(DataInputStream.java:570)
28.06.2024 - 16:11:57 - 	at com.google.common.io.ByteStreams$ByteArrayDataInputStream.readUTF(ByteStreams.java:456)
28.06.2024 - 16:11:57 - 	at me.neznamy.tab.shared.features.redis.message.PlayerJoin.read(PlayerJoin.java:49)
28.06.2024 - 16:11:57 - 	at me.neznamy.tab.shared.features.redis.message.Load.read(Load.java:34)
28.06.2024 - 16:11:57 - 	at me.neznamy.tab.shared.features.redis.RedisSupport.lambda$processMessage$1(RedisSupport.java:70)
28.06.2024 - 16:11:57 - 	at me.neznamy.tab.shared.cpu.TimedCaughtTask.run(TimedCaughtTask.java:28)
28.06.2024 - 16:11:57 - 	at me.neznamy.tab.shared.cpu.CaughtTask.run(CaughtTask.java:18)
28.06.2024 - 16:11:57 - 	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
28.06.2024 - 16:11:57 - 	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
28.06.2024 - 16:11:57 - 	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304)
28.06.2024 - 16:11:57 - 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
28.06.2024 - 16:11:57 - 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
28.06.2024 - 16:11:57 - 	at java.base/java.lang.Thread.run(Thread.java:833)
28.06.2024 - 16:13:21 - [TAB v5.0.0-SNAPSHOT] Unable to unregister team of redis player MoonxLightss on quit, because team is null

**Comment by MacTh3Mac** [comment]
Yes multi players on same proxy display correctly.  even when on different grouped servers.

**Comment by quiquelhappy** [comment]
we see similar issues in which we see white names every now and then. we have 5 proxies, all with the *exact same versions* (we deploy them using git with exactly the same configuration). the only change factor between proxies is the ping to redis node. some instances can have up to 300ms ping to our redis node - i dont know if that could be a factor causing parsing not to be working correctly.

also (maybe I should create a different issue but it seems it could fit in this issue scope) - spectator mode for players on different servers is not applied when they are on a different proxy, and they show as normal players instead of spectator players.

**Comment by NEZNAMY** [comment]
> we see similar issues in which we see white names every now and then. we have 5 proxies, all with the _exact same versions_ (we deploy them using git with exactly the same configuration). the only change factor between proxies is the ping to redis node. some instances can have up to 300ms ping to our redis node - i dont know if that could be a factor causing parsing not to be working correctly.
> 
> also (maybe I should create a different issue but it seems it could fit in this issue scope) - spectator mode for players on different servers is not applied when they are on a different proxy, and they show as normal players instead of spectator players.

Is that with 4.1.6 or 5.0.0? The spectator thing is a missing feature that I will add.

**Comment by quiquelhappy** [comment]
4.1.6

**Comment by NEZNAMY** [comment]
Then it makes sense that the bug reported in version 4.1.6 is present in 4.1.6.

**Comment by MacTh3Mac** [comment]
Confirm that on V5.0 when on all same version, tablist formatting applies as expected.  Vanished player support seems to be inconsistent or broken, but no errors generated, TAB installed on front and back ends.  Thanks

**Comment by NEZNAMY** [comment]
Mixed installation is unsupported and will result in issues.
