### ISSUE TITLE
Assigning groups to operators

### ISSUE THREAD

**Issue by Po-C4** [NEZNAMY/TAB#146]
**Server version**
Paper 1.15.2 v239

**Plugin version** ("latest" is not a version)
v2.7.4

**Describe the bug**
When we assign groups by permission, operators have by default access to every groups, so only the highest ranking one will be displayed.

**How to reproduce**
In advancedconfig.yml enable _assign-groups-by-permissions_ and make yourself an operator.

**Expected behavior**
Only assigned groups should be displayed.

**Comment by Tanguygab** [comment]
well when you are OP you have all permissions, so it's normal that you have the highest group.
Disable the sorting by permissions option and sort by groups instead or deny the `tab.sort.*` permission for all OP so they will only have access to the one they have (idk if it's the same with other plugins but I guess it is, but in LuckPerms, if you have a wildcard (*) other permissions will overrides it so if you have tab.sort.group1 but have negated tab.sort.* then you will only have the group1 assigned because the wildcard will deny all groups and group1 will override the wildcards)

**Comment by mashmarvin** [comment]
Also there is an option to disable OPs in LuckPerms config
https://github.com/lucko/LuckPerms/wiki/Configuration#enable-ops

**Comment by Po-C4** [comment]
I'm using LuckPerms and to fix this issue I'm putting `tab.group.*` to false for operators and then I give them the permission for the group I want to display. But it would be nice if by default operators would not have access to every groups.

**Comment by NEZNAMY** [comment]
This is what OP is for - for all permissions. Disable sorting by permissions or negate permissions if you need it. Not a bug, this is intentional.

**Comment by Tanguygab** [comment]
> I'm using LuckPerms and to fix this issue I'm putting `tab.group.*` to false for operators and then I give them the permission for the group I want to display. But it would be nice if by default operators would not have access to every groups.

well by default sorting is by groups not permissions, so OP don't have all permissions

**Comment by Po-C4** [comment]
Ok I will manage with that then
