### ISSUE TITLE
See own nametags

### ISSUE THREAD

**Issue by NiceKype** [NEZNAMY/TAB#269]
Is it currently somehow possible or as a new feature to see your own tags above your head? Usually a tag of myself is shown when I go to the third person for example. It's not really nice that others can see my tags like my rank and deluxe tags, but not me.

If that is not possible currently i want to make this as a suggestion for a new feature.

**Comment by NEZNAMY** [comment]
Hacked client or with unlimited nametag mode use /tab ntpreview. There is no other way with a plugin.

**Comment by NiceKype** [comment]
What you mean with hacked client?
I have the unlimited nametag mode on, i try that command later.

**Comment by NEZNAMY** [comment]
I don't know any, it's been a while since I was cheating on a server. Try google.

**Comment by NiceKype** [comment]
Why Hack Clients? Its about your plugin, nothing to do with hacked clients.
See my own tags above the head as on any other server too xD

**Comment by NEZNAMY** [comment]
Mojang made the game not render your own nametag.

**Comment by NiceKype** [comment]
🤔
Its possible on every server i know. I can see my name too if im in third person.

**Comment by NEZNAMY** [comment]
Ask them how did they do it without armor stands on vanilla client.

**Comment by Tanguygab** [comment]
> 🤔
> Its possible on every server i know. I can see my name too if im in third person.

That's because you are using a custom client (what NEZNAMY refers to "hacked" client)  
With the default Minecraft launcher, without any mods, you can't see your own nametag. Some custom clients support that tho but they are not compatible with the Unlimited Nametag Mode from TAB as this feature hides the player's nametag and shows Armor Stands instead. You can make the plugin show your own nametag thanks to the `/tab ntpreview` command, but it is not recommended if your goal isn't to do some tests with the plugin, it is very delayed with the player and thus, will simply annoy players instead. This cannot be made perfectly synchronised, but if you look at other players, it will be normal

**Comment by NiceKype** [comment]
Oh weared, i was so confused because i played everytime with labymod but i though that was normal in minecraft.
But thanks, now i know it was only because i used labymod.
Thanks for help!
