### ISSUE TITLE
Tab does not update when player changes group

### ISSUE THREAD

**Issue by Trinchezito** [NEZNAMY/TAB#525]
### Server version

1.18.1

### TAB version

3.1.0

### Describe the bug

On 3.1.0 the tab does not update when a player changes group. He has to log out and log back in so the group on the tab gets changed.

On 3.0.2 this does not occur. The tab auto updates when the player changes group. 

### Expected behavior

Auto updates the tab

### Steps to reproduce

1. have 2 groups with custom tab prefix.
2. change the player group
3. It wont change the group in the tab
4. player have to log out and log back in to see the changes in the tab

### Checklist

- [X] I am running latest version of the plugin
- [X] I have read the wiki to make sure it's not an issue with configuration
- [X] I have read the Compatibility wiki page and am not trying to run the plugin on an unsupported server version / platform

**Comment by NEZNAMY** [comment]
Will be fixed in the next version.

**Comment by antasetyawan** [comment]
i have same issue :
09.03.2022 - 22:11:18 - [TAB v3.1.0] An error was thrown when executing task
09.03.2022 - 22:11:18 - java.lang.NullPointerException: null
10.03.2022 - 12:01:11 - [TAB v3.1.0] An error was thrown when executing task
10.03.2022 - 12:01:11 - java.lang.NullPointerException: Cannot invoke "me.neznamy.tab.api.placeholder.PlaceholderManager.detectPlaceholders(String)" because the return value of "me.neznamy.tab.api.TabAPI.getPlaceholderManager()" is null
10.03.2022 - 12:01:11 - 	at TAB v3.1.0.jar//me.neznamy.tab.shared.placeholders.TabPlaceholder.getNestedPlaceholders(TabPlaceholder.java:102)
10.03.2022 - 12:01:11 - 	at TAB v3.1.0.jar//me.neznamy.tab.shared.placeholders.TabPlaceholder.setPlaceholders(TabPlaceholder.java:136)
10.03.2022 - 12:01:11 - 	at TAB v3.1.0.jar//me.neznamy.tab.shared.placeholders.PlayerPlaceholderImpl.update(PlayerPlaceholderImpl.java:55)
10.03.2022 - 12:01:11 - 	at TAB v3.1.0.jar//me.neznamy.tab.shared.features.PlaceholderManagerImpl.updatePlayerPlaceholder(PlaceholderManagerImpl.java:121)
10.03.2022 - 12:01:11 - 	at TAB v3.1.0.jar//me.neznamy.tab.shared.features.PlaceholderManagerImpl.refresh(PlaceholderManagerImpl.java:67)
10.03.2022 - 12:01:11 - 	at TAB v3.1.0.jar//me.neznamy.tab.shared.CpuManager.lambda$runMeasuredTask$8(CpuManager.java:353)
10.03.2022 - 12:01:11 - 	at TAB v3.1.0.jar//me.neznamy.tab.shared.CpuManager.lambda$submit$1(CpuManager.java:115)
10.03.2022 - 12:01:11 - 	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
10.03.2022 - 12:01:11 - 	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
10.03.2022 - 12:01:11 - 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
10.03.2022 - 12:01:11 - 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
10.03.2022 - 12:01:11 - 	at java.base/java.lang.Thread.run(Thread.java:833)
10.03.2022 - 12:01:19 - [TAB v3.1.0] An error was thrown when executing task
10.03.2022 - 12:01:19 - java.lang.NullPointerException: null

After player login, the placeholder not refresh and player cant see the placeholder

**Comment by NEZNAMY** [comment]
This error is not realated to this issue in any way.
