### ISSUE TITLE
Know which method edit which name

### ISSUE THREAD

**Issue by Elikill58** [NEZNAMY/TAB#54]
Hello,
I'm a developer and i'm trying to use your API.
There is a lot of method to set names, but i don't really know which method correspond to which names.
I found how to edit name showed in TAB (like here: http://prntscr.com/ph5aaz) but i don't know how to edit the name just below the player.
Can you explain it on the Wiki ?

**Comment by NEZNAMY** [comment]
It works just like it does in config. Same identifiers, such as "tabprefix" - being prefix in tablist. What should i add there ? I thought everything is obvious.

**Comment by Elikill58** [comment]
What is the difference between:
CustomTab
Tab
OriginalTab ?
Is the "AboveName" correspond to what i want to edit ?

**Comment by NEZNAMY** [comment]
The names are just like in config.
tabprefix = prefix in tablist
tabsuffix = prefix in tablist
tagprefix = prefix in nametag
tagsuffix = prefix in nametag
customtabname = if present, using that value instead of player's name in tablist

Other ones which need unlimited nametag mode:
abovename = line of text above player's nametag
belowname = line of text below player's nametag
customtagname = if present, using that value insteaf of player's name in nametag

Temporarily = until the next restart/reload
Permanently = saved into config too

For the "original" values, they are player's original values before applying changes made by the API.

**Comment by Elikill58** [comment]
Hello,

Ok, that's good !
I was talking about the "tagprefix" :)
