### ISSUE TITLE
From time to time the default TAB screen appears for 1 second. 

### ISSUE THREAD

**Issue by boodmi** [NEZNAMY/TAB#609]
### Server version

Paper 1.18.1-216

### TAB version

3.1.1

### Describe the bug

From time to time the default TAB screen appears for 1 second. 
![unknown](https://user-images.githubusercontent.com/34908221/170662640-bdcdf6ca-930a-4ef8-9c8e-24a7ddae0cc0.png)

### Expected behavior

TAB must match the config all the time

![изображение](https://user-images.githubusercontent.com/34908221/170664306-1ab51083-c9db-4799-8934-807d6d5b598e.png)

### Steps to reproduce

No action, just play

### Checklist

- [X] I am running latest version of the plugin
- [X] I have read the wiki to make sure it's not an issue with configuration
- [X] I have read the Compatibility wiki page and am not trying to run the plugin on an unsupported server version / platform

**Comment by Tanguygab** [comment]
/plugins/CMI/modules.yml -> tabList: false

**Comment by NEZNAMY** [comment]
Anti-override for header/footer does not exist, because it caused high CPU usage and had no real advantages. This is not a bug, but an intentionally missing function for the best for everyone. Disabling header/footer in CMI is rather simple and not having to do it isn't worth the possible drastic CPU usage increase for everyone.

**Comment by boodmi** [comment]
Thanks
