### ISSUE TITLE
Pelase add support for mc 1.19.2

### ISSUE THREAD

**Issue by RZSrzTeam** [NEZNAMY/TAB#757]
### Server version

Paper 1.19.2

### TAB version

LTS

### Stack trace

Pelase add support for mc 1.19.2

### Checklist

- [X] I am running latest version of the plugin
- [X] I have included a paste of the error
- [X] I ticked all of the boxes without actually reading them
- [X] I have read the Compatibility wiki page and am not trying to run the plugin on an unsupported server version / platform

**Comment by 4drian3d** [comment]
Have you already checked https://github.com/NEZNAMY/TAB/wiki/Compatibility#supported-server-versions ? *Yes, TAB supports Minecraft 1.19.2*

**Comment by Tanguygab** [comment]
![20221211_071248.jpg](https://user-images.githubusercontent.com/45695833/206889237-c9e8d0d7-6f80-4218-8aaa-b504cbbe292d.jpg)
You haven't provided your TAB version(LTS or latest is not an answer)
You haven't provided any errors showing issues with 1.19.2
You literally ticked all the box without looking
And you clearly didn't read the Compatibility page.

Now, if you do encounter issues with 1.19.2, make sure you actually agree on the latest release(3.1.5 as of now). If you still have issues, send errors, provide more info.
If you are using 1.19.3, this version is not supported yet, you can keep track of the development in #754 (Please DO NOT ask "pls add support for 1.19.3" again, we now you want it, that's why we made that ticket, it's coming, don't worry)
