### ISSUE TITLE
Packet encoding of packet ID 78 threw (skippable? false)

### ISSUE THREAD

**Issue by AVuTuVA** [NEZNAMY/TAB#844]
### Server version

Purpur 1.19.3

### TAB version

3.3.2-SNAPSHOT

### Stack trace

https://yaso.su/errortab

### Steps to reproduce (if known)

Kicks players at random

### Additional info

https://github.com/dmulloy2/ProtocolLib/issues/2094

### Checklist

- [X] I am running latest version of the plugin
- [X] I have included a paste of the error
- [ ] I ticked all of the boxes without actually reading them
- [X] I have read the Compatibility wiki page and am not trying to run the plugin on an unsupported server version / platform

**Comment by Tanguygab** [comment]
https://support-system.xyz/redirect?link=https://cdn.discordapp.com/attachments/690574378454483034/1086589951606534154/ticket-1086584630792163339.html

**Comment by DIDIRUS4** [comment]
> The error in the issue you linked is different from yours, and is due to a bug in an old TAB version, which has since been fixed. https://support-system.xyz/redirect?link=https://cdn.discordapp.com/attachments/690574378454483034/1086589951606534154/ticket-1086584630792163339.html As mentioned in the ticket, TAB shouldn't affect this, try again without it

But, he's using last version from actions.....

**Comment by Tanguygab** [comment]
There's 3 errors:
- 2 from the ProtocolLib ticket
- 1 that @AVuTuVA sent

The first one in the ProtocolLib ticket is apparently completely unrelated to TAB.
The second was because of an issue in older TAB version which has been fixed ever since
And @AVuTuVA's error (which is different from the other two) is not related to TAB at all. In the ticket transcript I linked, you can see another user with the same error, though since the error concerns items (that TAB doesn't manage at all), it is unlikely that TAB affects it.

**Comment by NEZNAMY** [comment]
TAB is not modifying ItemStacks.
