### ISSUE TITLE
Footer Gradient is not smooth

### ISSUE THREAD

**Issue by ScaredRabbitYT** [NEZNAMY/TAB#887]
### Server version

Paper 1.19.2

### TAB version

3.3.2

### Describe the bug

I have a gradient on my TabList, but on the footer part it is not completely smooth like the header part.
![header_footer](https://user-images.githubusercontent.com/103259379/236474106-a15a2f4b-f38c-4b90-bfc5-f22c652e1862.png)

### Expected behavior

I wanted the footer gradient to be smooth like the header gradient.

### Steps to reproduce

Step 1: Download the config and animations.yml (linked) and place it in the ~/plugins/TAB folder of your server
Step 2: Start your server and join it, then press the Tab key (Or the key you bound the tablist to) on your keyboard.
[TAB.zip](https://github.com/NEZNAMY/TAB/files/11406679/TAB.zip)

### Checklist

- [X] I am running latest version of the plugin
- [X] I have read the wiki to make sure it's not an issue with configuration
- [ ] I ticked all of the boxes without actually reading them
- [X] I have read the Compatibility wiki page and am not trying to run the plugin on an unsupported server version / platform

**Comment by Tanguygab** [comment]
![image](https://user-images.githubusercontent.com/45695833/236475994-5cceacb5-21cf-446e-a7ce-0accc8d35bf7.png)
looks fine to me, I tried on Paper 1.19.4 with both TAB 3.2.2 and 4.0.0
Not sure what's wrong, but if you want an alternative, try to replace all instances of `━` in your animations.yml file by a space, and it should work fine (since you already have the strikethrough with &m)

**Comment by ScaredRabbitYT** [comment]
Thank you, ith works now!
