### ISSUE TITLE
Request support for mohist 1.19.2

### ISSUE THREAD

**Issue by Test031** [NEZNAMY/TAB#940]
### Server version

mohist-1.19.2-25

### TAB version

4.0.1

### Describe the bug

[TAB] Your server version is marked as compatible, but a compatibility issue was found. Please report this issue (include your server version & fork too)

### Expected behavior

Request support for mohist 1.19.2

### Steps to reproduce

Request support for mohist 1.19.2

### Checklist

- [X] I am running latest version of the plugin
- [X] I have read the wiki to make sure it's not an issue with configuration
- [ ] I ticked all of the boxes without actually reading them
- [X] I have read the Compatibility wiki page and am not trying to run the plugin on an unsupported server version / platform

**Comment by NEZNAMY** [comment]
Mohist is using a mapping system like no other software. Use magma, or ask them to use bukkit mappings.

**Comment by Test031** [comment]
I can't find the download address of Magma, could you please tell me?

**Comment by NEZNAMY** [comment]
https://magmafoundation.org/

**Comment by NEZNAMY** [comment]
As per [compatibility page](https://github.com/NEZNAMY/TAB/wiki/Compatibility) mohist versions higher than 1.16.5 are not supported due to wrong mappings in their software. It is unclear whether they are going to fix it or not, but for now, assuming it's not ready for production and therefore not going to try to use their mappings.
